"""Machine verification of every lemma in the proof of the class formula
sigma_hat[f] = [r_n][f]^{-1}  (see class-formula-proof.md).

For each primitive reduced form f = (a,b,c) of disc D = 1 - n^2 (n odd):

Lemma A: with K = {(s,t): (n+1)s = bt, bs = -(n-1)t mod 2a} (index a in Z^2),
  an oriented basis w_1, w_2 of K (t_1 s_2 - s_1 t_2 = a), u_k = s_k + i t_k,
  v_k = ((n+bi)u_k + conj(u_k)) / (2ia), the matrix P with columns
  (u_1, u_2)^T, (v_1, v_2)^T lies in SL_2(Z[i]) and P^dagger M_0 P = M_f.

Lemma B: the sigma-image Gram M' = -conj((P^{-1})^dagger M_0 P^{-1}) has
  real part given by the form (1/2a) g|_K, g(s,t) = (n+1)s^2 + (n-1)t^2,
  in the basis determined below, and Im-part +-n.

Lemma C: the map (s,t) -> s(n+1)/2 + t*omega identifies K with an
  O-ideal c (omega-stable), and c = s_ideal * a_f, where
  s_ideal = ((n+1)/2, omega), a_f = (a, b/2 + omega).

Conclusion: the image class is compose(r_n, f)^{op} = r_n o f^{-1}.
"""
import sys
sys.path.insert(0, 'scripts')
from involution_experiments import (I2, M0, matmul, dagger, det, inv_sl2,
                                    sigma, M_of_X, herm_from_triple,
                                    herm_triple, gm, ga, gc)
from involution_classmap import (classes_of_disc, reduce_form, opp, compose,
                                 inverse, oriented_data, is_primitive)
from math import gcd


def K_basis(n, a, b):
    """Oriented basis (t1*s2 - s1*t2 = a) of the congruence lattice K."""
    m = 2 * a
    pts = [(s, t) for s in range(m) for t in range(m)
           if ((n + 1) * s - b * t) % m == 0 and (b * s + (n - 1) * t) % m == 0]
    # lattice generated by pts and (m,0),(0,m): HNF via simple reduction
    gens = pts + [(m, 0), (0, m)]
    # 2D HNF
    from math import gcd as _g
    # find primitive vector along first column structure: use standard algo
    import itertools
    # reduce: bring to basis via repeated gcd steps
    basis = []
    v1 = None
    # first basis vector: gcd of all s-components with combos
    # simple approach: use Smith-like reduction on the generator matrix
    rows = gens[:]
    # HNF of the lattice spanned by rows (as row lattice in Z^2)
    def hnf(rows):
        rows = [list(r) for r in rows if r != (0, 0)]
        # make column 0 have a single nonzero via gcd
        while True:
            nz = [r for r in rows if r[0] != 0]
            if len(nz) <= 1:
                break
            nz.sort(key=lambda r: abs(r[0]))
            p = nz[0]
            for r in nz[1:]:
                q = r[0] // p[0]
                r[0] -= q * p[0]
                r[1] -= q * p[1]
            rows = [r for r in rows if r != [0, 0]]
        top = [r for r in rows if r[0] != 0]
        rest = [r for r in rows if r[0] == 0]
        assert len(top) == 1
        while True:
            nzz = [r for r in rest if r[1] != 0]
            if len(nzz) <= 1:
                break
            nzz.sort(key=lambda r: abs(r[1]))
            p = nzz[0]
            for r in nzz[1:]:
                q = r[1] // p[1]
                r[1] -= q * p[1]
            rest = [r for r in rest if r != [0, 0]]
        sec = [r for r in rest if r[1] != 0]
        assert len(sec) == 1
        return top[0], sec[0]
    b1, b2 = hnf(rows)
    w1, w2 = tuple(b1), tuple(b2)
    d = w1[1] * w2[0] - w1[0] * w2[1]          # t1*s2 - s1*t2
    assert abs(d) == a, (n, a, b, d)
    if d == -a:
        w2 = (-w2[0], -w2[1])
    return w1, w2


def gauss(re, im):
    return (re, im)


def build_P(n, f):
    a, b, c = f
    (s1, t1), (s2, t2) = K_basis(n, a, b)
    u1, u2 = (s1, t1), (s2, t2)                 # u_k = s_k + i t_k

    def v_of(u):
        # ((n + b i)(s + t i) + (s - t i)) / (2 i a)
        s, t = u
        num = ((n + 1) * s - b * t, b * s + (n - 1) * t)
        # divide by 2ia = (0, 2a): 1/(2ia) = -i/(2a)
        # num * (-i) = (num_im, -num_re)
        z = (num[1], -num[0])
        assert z[0] % (2 * a) == 0 and z[1] % (2 * a) == 0, (n, f, u)
        return (z[0] // (2 * a), z[1] // (2 * a))
    v1, v2 = v_of(u1), v_of(u2)
    P = ((u1, v1), (u2, v2))                    # columns (u1,u2), (v1,v2)
    assert det(P) == (1, 0), (n, f)
    Mf = herm_from_triple(2 * a, (b, -n), 2 * c)
    assert matmul(dagger(P), matmul(M0, P)) == Mf, (n, f)
    return P, ((s1, t1), (s2, t2))


def omega_action(n, w):
    """omega * (s,t) in the coordinates (s,t) <-> s(n+1)/2 + t omega."""
    s, t = w
    return ((1 - n) * t // 2, (n + 1) * s // 2)


def lattice_eq(gens1, gens2, box=None):
    """Equality of 2D lattices given generators (integer pairs)."""
    def hnf2(gens):
        rows = [list(g) for g in gens if g != (0, 0)]
        while True:
            nz = [r for r in rows if r[0] != 0]
            if len(nz) <= 1:
                break
            nz.sort(key=lambda r: abs(r[0]))
            p = nz[0]
            for r in nz[1:]:
                q = r[0] // p[0]
                r[0] -= q * p[0]; r[1] -= q * p[1]
            rows = [r for r in rows if r != [0, 0]]
        top = [r for r in rows if r[0] != 0]
        rest = [r for r in rows if r[0] == 0 and r[1] != 0]
        while len(rest) > 1:
            rest.sort(key=lambda r: abs(r[1]))
            p = rest[0]
            for r in rest[1:]:
                q = r[1] // p[1]
                r[1] -= q * p[1]
            rest = [r for r in rest if r[1] != 0]
        t0 = top[0]
        s0 = rest[0] if rest else [0, 0]
        if s0 != [0, 0]:
            t0 = [t0[0], t0[1] % abs(s0[1])] if s0[1] else t0
        if t0[0] < 0:
            t0 = [-t0[0], -t0[1]]
        if s0[1] < 0:
            s0 = [0, -s0[1]]
        if s0[1]:
            t0[1] %= s0[1]
        return (tuple(t0), tuple(s0))
    return hnf2(gens1) == hnf2(gens2)


def run(nmax=25):
    total = 0
    for n in range(3, nmax + 1, 2):
        D = 1 - n * n
        rn = reduce_form((n - 1) // 2, 0, (n + 1) // 2)
        for f in classes_of_disc(D):
            if not is_primitive(f):
                continue
            a, b, c = f
            P, (w1, w2) = build_P(n, f)              # Lemma A
            X = inv_sl2(P)
            eps2, yM2, f2 = oriented_data(M_of_X(sigma(X)))
            assert yM2 == n and eps2 == -1

            # Lemma B: predicted image form from g|_K
            def g(w, w_=None):
                s, t = w
                s_, t_ = w_ if w_ else w
                return (n + 1) * s * s_ + (n - 1) * t * t_
            a2, c2 = g(w2), g(w1)
            b2 = g(w1, w2)
            assert a2 % (2 * a) == 0 and c2 % (2 * a) == 0 and (2 * b2) % (2 * a) == 0
            fB = reduce_form(a2 // (2 * a), -b2 // a, c2 // (2 * a))
            assert fB == f2, (n, f, fB, f2)

            # Lemma C: K is omega-stable, and c = s_ideal * a_f
            for w in (w1, w2):
                ww = omega_action(n, w)
                # membership in K: solve integer combo of basis
                dd = w1[1] * w2[0] - w1[0] * w2[1]
                x = (ww[1] * w2[0] - ww[0] * w2[1])
                y = (w1[1] * ww[0] - w1[0] * ww[1])
                assert x % dd == 0 and y % dd == 0, (n, f, w)
            # generators of s_ideal * a_f in (s,t)-coordinates:
            prod_gens = [
                (a, 0),                              # (n+1)/2 * a
                (b // 2, (n + 1) // 2),              # (n+1)/2 * (b/2 + omega)
                (0, a),                              # a * omega
                ((1 - n) // 2, b // 2),              # (b/2 + omega) * omega
            ]
            assert lattice_eq(prod_gens, [w1, w2]), (n, f)

            # Conclusion: image class = (r_n o f)^{op} = r_n o f^{-1}
            assert f2 == opp(compose(rn, f, D)) == compose(rn, inverse(f), D)
            total += 1
    print(f"all lemmas verified on {total} primitive classes (odd n <= {nmax})")


if __name__ == "__main__":
    run(int(sys.argv[1]) if len(sys.argv) > 1 else 25)
